#define Nk 8        //число каналов связи
#define Nst 8       //число стоек ТУМС
#define Narm 6    //число АРМов + 1
#define Nranj 2 //число районов управления
#define SIZE_BUF 100 //размер кольцевых буферов ввода и вывода
#define KANAL 1
#define OBJECT 2
#define ANALIZ 3
#define KONFIG 4
#define COMMAND 5
#define ANAL_MARSH 6
#define WORK 1
#define ARM_SHN 9 //номер АРМа ШН
#define PEREDANO 0x1F  // маска передачи в имеющиеся АРМы
#define TEST 1
#define MAX_NEW 40
